// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysclgytazmjkugryajfj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzY2xneXRhem1qa3VncnlhamZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE3Nzk4OTEsImV4cCI6MjA1NzM1NTg5MX0.J80e25TcuYJT1Yvy4N-q6BB8pfROJvGo-024dqGSws8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Revert to original configuration to fix connection issues
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);